export const PASSPORT_ERROR: Record<string, string> = {
  too_many_attempts: 'Слишком много попыток, попробуйте позже',
  terms_not_accepted: 'Правила и Условия использования не были приняты',
  invalid_phone_number: 'Неверный номер телефона',
  invalid_phone_number_length: 'Неверная длина номера телефона',
  get_user_id_by_phone_failed: 'Не удалось получить идентификатор пользователя по телефону',
  get_resource_failed: 'Не удалось получить ресурс',
  only_employee_can_access: 'Только сотрудник может получить доуступ к ресурсу',
  resource_disallowed_by_login_type: 'Неверный номер телефона',
  generate_otp_failed: 'Не удалось получить одноразовый код',
  notify_client_failed: 'Не удалось отправить код',
  incorrect_code: 'Неверный код подтверждения',
  no_data_sent: 'Требуемые данные не отправлены',
  invalid_country_field: 'Неверное значение в поле "Страна"',
  invalid_device_field: 'Неверное значение в поле "Устройство"',
  invalid_version_field: 'Неверное значение в поле "Версия"',
  invalid_resource: 'Неверный ресурс',
  create_user_failed: 'Создать пользователя не удалось',
  invalid_code_length: 'Неверная длина СМС кода',
  check_otp_failed: 'Проверка СМС кода не пройдена',
  session_already_created: 'Сессия уже запущена',
  new_session_failed: 'Не удалось запустить сессию',
  invalid_token: 'Неверные данные доступа',
  invalid_resource_id: 'Неверные номер ресурса',
  put_resource_failed: 'Неверные номер ресурса',
  resource_not_defined: 'Нельзя определить ресурс',
  unauthorized: 'Неавторизованный пользователь',
  authentication_failed: 'Ошибка аутентификации',
  invalid_auth_code: 'Неверный код аутентификации',
  internal_authentication_error: 'Внутренняя ошибка аутентификации',
  external_authentication_error: 'Внешняя ошибка аутентификации',
  invalid_cookie_value: 'Неверное значение данных сессии',
  get_user_session_list_failed: 'Невозможно получить список сессий пользователя',
  close_session_failed: 'Невозможно завершить сессию',
  get_user_failed: 'Не удалось получить данные пользователя',
  phone_not_confirmed: 'Номер телефона не подтвержден',
  patch_user_failed: 'Не удалось обновить данные пользователя',
  phone_already_confirmed: 'Номер телефона уже подтвержден',
  invalid_options: 'Недостаточно данных',
  get_access_code_failed: 'Не удалось проверить код доступа',
} as const;
