export const CUSTOM_ERRORS: Record<string, string> = {
  'name is used': 'Название уже используется',
  'no rows affected': 'Объект не найден',
  'method not allowed': 'Недостаточно прав',
  'user not found': 'Пользователь не найден',
  'global permission denied': 'Недостаточно прав',
  'service permission denied': 'Недостаточно прав',
  'resource inactive': 'Ресурс не активен',
  "it's impossible": ',Действие недоступно',
  'quota less than consumption': 'Потребление превышает квоту',
  'requested quota bigger than existed': 'Объем квоты недостаточен',
  'resource type is used': 'Тип ресурса используется в сервисе',
  'service type is used': 'Тип сервиса используется в сервисе',
  'folder type is used': 'Фолдер используется в сервисе',
  'tag is used': 'Невозможно удалить, тег используется в сервисе',
  "you are not owner or entity doesn't exist": 'Недостаточно прав',
  'validation error: quota is lower than or equal to zero': 'Квота не может быть меньше нуля',
  'validation error: not allowed for bot permission': 'Недостаточно прав',
  'not found': 'Объект не найден',
  'service has dependent entities': 'Удаление невозможно при наличии зависимостей',
  'service inactive': 'Сервис не активен',
  'service is already archived': 'Сервис находится в архиве',
  'service is already unarchived': 'Сервис не находится в архиве',
  'service is archived': 'Сервис находится в архиве',
  'service is not infrastructure': 'Сервис не является инфраструктурным',
  'service not archived': 'Сервис не находится в архиве',
  'service not found or not archived': 'Сервис не найден или не находится в архиве',
  'resource has consumers': 'Ресурс используется',
  'group is default': 'Группа является системной',
  'service role is default': 'Роль является системной',
  'resource is archived': 'Ресурс находится в архиве',
  'resource not found or not archived': 'Ресурс не найден или в не архиве',
  'config unit group is used': 'Невозможно удалить, группа используется',
  'invalid excel file data': 'Некорректные данные',
  'parent service not found': 'Сервис-родитель не найден',
  'short name empty': 'Не заполнено короткое название сервиса',
  'status invalid': 'Некорректный статус сервиса',
  'category invalid': 'Некорректная категория сервиса',
  'criticality invalid': 'Некорректная критичность сервиса',
  'empty excel': 'Пустой файл',
  'sheet service_create does not exist': 'Неправильное название файла',
};
